server:
  port: 8080

sentry:
  dsn: ""
  environment: "production"
  # It is recommended to lower this value from the default of 1.0 on production
  traces-sample-rate: 1.0

decorator:
  datasource:
    p6spy:
      enable-logging: false

spring:
  application:
    name: "RepositoryManager"
  datasource:
    url: jdbc:h2:file:./data/database;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: danbo
    password: danbo

repository-manager:
  base-url: "http://localhost:8080"
  default-platform: "wii"
  repo-dir: "repository"
  discord:
    enable-logging: false
    catalog-webhook-url: ""
    log-webhook-url: ""
    mod-webhook-url: ""
  fetch:
    timeout: 60
    user-agent: "RepositoryManager-DEV"
    secret-user-agents: {}
    github-token: ""
    itchio-token: ""
  mail:
    sender-address: "no-reply@example.com"
    sendgrid-api-key: ""
  security:
    allow-registration: false
    protected-users: [1]
    secret-key: "ChangeMe"
  shop:
    generate-banner: false
    banner-generator-path: "BannerGenerator"
    banner-output-path: "data/titles/"

logging:
  level:
    org.springframework: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate: WARN
    org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: ERROR
    org.springframework.web.SimpLogging: ERROR
    com.github.junrar: ERROR
    # org.springframework.beans: TRACE
    # org.oscwii.repositorymanager.security: TRACE
    # org.springframework.security: TRACE