server:
  port: 8080

sentry:
  dsn: ""

spring:
  application:
    name: "RepositoryManager"
  datasource:
    url: jdbc:h2:file:./data/database;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: danbo
    password: danbo

repository-manager:
  base-url: "http://localhost:8080"
  default-platform: "wii"
  repo-dir: "repository"
  generate-wsc-banner: false
  banner-generator-path: "BannerGenerator"
  discord:
    enable-logging: false
    catalog-webhook-url: ""
    log-webhook-url: ""
  fetch:
    timeout: 60
    user-agent: "RepositoryManager-DEV"
    secret-user-agents: {}
    github-token: ""
    itchio-token: ""
  mail:
    sender-address: "no-reply@example.com"
    sendgrid-api-key: ""
  security:
    allow-registration: false
    protected-users: [1]
    secret-key: "ChangeMe"

logging:
  level:
    org.springframework: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate: WARN
    com.github.junrar: ERROR
    # org.springframework.beans: TRACE
    # org.oscwii.repositorymanager.security: TRACE
    # org.springframework.security: TRACE